### ISSUE TITLE
Repo runner script on QA droplet throwing 'couldn't find remote ref release'

### ISSUE THREAD

**Issue by mig5** [freedomofpress/securedrop-yum-prod#48]
Wanted to note that the sd-qubes-dom0-repo-qa droplet is throwing these errors in the runner.sh since at least late October (maybe earlier):

```
Nov 23 23:00:01 sd-qubes-dom0-repo-qa systemd[1]: Started lfs-repo-webhook-runner.service - Run LFS-repo script until finished, as a singleton.
Nov 23 23:00:01 sd-qubes-dom0-repo-qa runner.sh[4979]: INFO:yum-auto-publish:Fetching latest git info
Nov 23 23:00:19 sd-qubes-dom0-repo-qa runner.sh[4987]: Already on 'release'
Nov 23 23:00:19 sd-qubes-dom0-repo-qa runner.sh[4987]: Your branch is up to date with 'origin/release'.
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[5014]: fatal: couldn't find remote ref release
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]: Traceback (most recent call last):
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:   File "/usr/local/bin/yum-auto-publish", line 248, in <module>
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:     repo.publish_on_changes(force=args.force)
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:   File "/usr/local/bin/yum-auto-publish", line 77, in publish_on_changes
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:     self.pull_repo()
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:   File "/usr/local/bin/yum-auto-publish", line 127, in pull_repo
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:     return subprocess.check_call(pull_cmd)
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:   File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]:     raise CalledProcessError(retcode, cmd)
Nov 23 23:00:20 sd-qubes-dom0-repo-qa runner.sh[4979]: subprocess.CalledProcessError: Command '['git', '-C', '/opt/yum-upstream-repos/securedrop-yum-prod', 'pull', 'origin', 'release']' returned non-zero
```

Seems it's because there's no 'release' branch here any more. Wasn't sure if this was known/expected already.

Should the script/config be changed for the 'QA' droplet? I note that prod follows 'main' of this repo. But maybe this is the normal setup and I'm only just noticing it.

@legoktm

**Comment by zenmonkeykstop** [comment]
IIRC the original intent (at least for the apt repos) was that `release` _would_ be deleted after merge, and a fresh one created for each PR (obviously this means that we can have 1 active release PR at a time, which may be a good or bad thing). I think the intent was that would reduce the chance of user error. 

I'd agree that falling back to `main` in cases where the repo needs rebuilding but `release` isn't available makes the most sense.
